### ISSUE TITLE
Register ClassImbalance in METADATA

### ISSUE THREAD

**Issue by dilumaluthge** [bcbi/ClassImbalance.jl#4]
Could we register ClassImbalance in the official METADATA?

**Comment by dilumaluthge** [comment]
@paulstey Did you get a chance to take a look at Attobot? The directions are here: https://github.com/attobot/attobot

**Comment by mirestrepo** [comment]
attobot is great! I use it for BioMedQuery and it really simplifies tagging new releases

**Comment by dilumaluthge** [comment]
@paulstey @mirestrepo Any update on tagging ClassImbalance?

**Comment by dilumaluthge** [comment]
Waiting on JuliaLang/METADATA.jl#13359

**Comment by dilumaluthge** [comment]
Done. See https://github.com/JuliaLang/METADATA.jl/commit/021844d46cb8c7352bebab202ed52a4a22e82176
